name: install
on: [push]
jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: npm-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            npm-
      - name: install-dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: npm install

  build-ts:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: npm-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            npm-
      - run: npm test

  run-tests:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.npm
          key: npm-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            npm-
      - run: npm test --coverage=true
<<<<<<< HEAD
      - uses: codecov/codecov-action@v2
=======
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_SECRET }}
>>>>>>> dbc6a7d (add secret for codecov)
